In [233]:
#Adapted from https://nbviewer.jupyter.org/github/empet/Plotly-plots/blob/master/Chord-diagram.ipynb?flush_cache=true

In [234]:
import plotly.plotly as py
import plotly.figure_factory as ff
import plotly.graph_objs as go
import numpy as np
import pandas as pd
import itertools

In [235]:
df = pd.read_csv('../dataframes/h3n2_ha_12y_hi_egg.csv')

In [236]:
#Spot check
print(len(df[(df['186']=='V') & (df['194']!='P') & 
             (df['138']!='S') & (df['246']!='H') & 
             (df['225']!='G') & (df['219']!='F') & 
             (df['219']!='Y') & (df['203']!='I') & 
             (df['156']!='R') & (df['156']!='Q')]))

49


In [237]:
sites = ['186','194','138','156','203','219','225', '246']
for site in sites:
    if site not in df.columns:
        sites.remove(site)
egg_muts = {'194': ['P'], 
            '186':['V'], '225':['G'], '219':['F','Y'], 
            '203':['I'], '156':['R','Q'], '138':['S'], 
            '246':['H']}
matrix = np.zeros((len(sites), len(sites)), dtype=int)
for site_a in sites:
    for site_b in sites:
        matrix_entry = 0
        #Set diagonal to be number of viruses with ONLY that mutation
        if site_a == site_b:
            only_sitea = 0           
            other_sites = sites.copy()
            other_sites.remove(site_a)
            for egg_genotype_a in egg_muts[site_a]:
                mask = df[site_a] == egg_genotype_a
                for other_site in other_sites:
                    for other_genotype in egg_muts[other_site]:
                        res = df[other_site] != other_genotype
                        mask &= res
                only_sitea += len(df[mask])
            matrix_entry= only_sitea
        #Find number of viruses with both egg mutations
        else:      
            for egg_genotype_a in egg_muts[site_a]:
                for egg_genotype_b in egg_muts[site_b]:
                    matrix_entry+= len(df[(df[site_a]==egg_genotype_a)&(df[site_b]==egg_genotype_b)])
        matrix[sites.index(site_a)][sites.index(site_b)] = matrix_entry

print(matrix)

[[ 49   0  21  34   0  59   8   8]
 [  0 122  14   0  23   3  14   0]
 [ 21  14  31  12   3   9  24   5]
 [ 34   0  12   8   0  12  11   1]
 [  0  23   3   0   0   1   1   0]
 [ 59   3   9  12   1   1   6   0]
 [  8  14  24  11   1   6   5   4]
 [  8   0   5   1   0   0   4   4]]


In [238]:
labels = ['186 V','194 P','138 S','156 R/Q','203 I','219 F/Y','225 G', '246 H']
ideo_colors = ['rgba(26,152,80, 0.75)',
               'rgba(215,48,39, 0.75)',
             'rgba(244,109,67, 0.75)',
             'rgba(253,174,97, 0.75)',
             'rgba(254,224,139, 0.75)',
             'rgba(217,239,139, 0.75)',
             'rgba(166,217,106, 0.75)',
             'rgba(102,189,99, 0.75)']

In [239]:
def check_data(data_matrix):
    L, M=data_matrix.shape
    if L!=M:
        raise ValueError('Data array must have (n,n) shape')
    return L

L=check_data(matrix)

In [240]:
radii_sribb=[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]# these value are set after a few trials 

In [241]:
def moduloAB(x, a, b): #maps a real number onto the unit circle identified with 
                       #the interval [a,b), b-a=2*PI
        if a>= b:
            raise ValueError('Incorrect interval ends')
        y = (x-a) % (b-a)
        return y+b if y < 0 else y+a

In [242]:
def test_2PI(x):
    return True
#      return 0 <= x < 2*pi

In [243]:
pi = np.pi

row_sum = [np.sum(matrix[k,:]) for k in range(L)]

#set the gap between two consecutive ideograms
gap = 2*pi*0.005
ideogram_length = 2*pi * np.asarray(row_sum) / sum(row_sum) - gap*np.ones(L)

In [244]:
def get_ideogram_ends(ideogram_len, gap):
    ideo_ends = []
    left = 0
    for k in range(len(ideogram_len)):
        right = left + ideogram_len[k]
        ideo_ends.append([left, right])   
        left = right + gap
    return ideo_ends 

In [245]:
ideo_ends = get_ideogram_ends(ideogram_length, gap)

In [246]:
def make_ideogram_arc(R, phi, a=100):
    # R is the circle radius
    # phi is the list of  angle coordinates of an arc ends
    # a is a parameter that controls the number of points to be evaluated on an arc
    if not test_2PI(phi[0]) or not test_2PI(phi[1]):
        phi = [moduloAB(t, 0, 2*pi) for t in phi]
    length = (phi[1]-phi[0]) % 2*pi 
    nr = 18 if length <= pi/4 else int(a*length/pi)

    if phi[0] < phi[1]:   
        theta = np.linspace(phi[0], phi[1], nr)
    else:
        phi = [moduloAB(t, -pi, pi) for t in phi]
        theta = np.linspace(phi[0], phi[1], nr)
    return R * np.exp(1j*theta)  

In [247]:
make_ideogram_arc(1.3, [11*pi/6, pi/17])

array([1.12583302-0.65j      , 1.13689513-0.6304518j ,
       1.14761784-0.61071539j, 1.15799797-0.59079667j,
       1.16803241-0.57070158j, 1.17771816-0.55043613j,
       1.18705234-0.53000636j, 1.19603216-0.50941837j,
       1.20465494-0.48867831j, 1.21291809-0.46779236j,
       1.22081917-0.44676677j, 1.22835581-0.42560781j,
       1.23552575-0.4043218j , 1.24232686-0.38291509j,
       1.24875711-0.36139407j, 1.25481458-0.33976517j,
       1.26049746-0.31803483j, 1.26580405-0.29620956j,
       1.27073277-0.27429586j, 1.27528215-0.25230028j,
       1.27945083-0.23022939j, 1.28323757-0.20808976j,
       1.28664123-0.18588801j, 1.2896608 -0.16363078j,
       1.29229537-0.14132469j, 1.29454417-0.11897642j,
       1.29640652-0.09659263j, 1.29788186-0.07418j   ,
       1.29896976-0.05174523j, 1.29966988-0.02929501j,
       1.29998203-0.00683605j, 1.2999061 +0.01562495j,
       1.29944212+0.03808129j, 1.29859022+0.06052626j,
       1.29735067+0.08295316j, 1.29572384+0.1053553j ,
       1.2

In [248]:
def map_data(data_matrix, row_value, ideogram_length):
    mapped = np.zeros(data_matrix.shape)
    for j  in range(L):
        mapped[:, j] = ideogram_length * data_matrix[:,j] / row_value
    return mapped  

In [249]:
mapped_data = map_data(matrix, row_sum, ideogram_length)
mapped_data

array([[0.39332711, 0.        , 0.16856876, 0.27292085, 0.        ,
        0.47359795, 0.06421667, 0.06421667],
       [0.        , 0.97893925, 0.11233729, 0.        , 0.18455412,
        0.02407228, 0.11233729, 0.        ],
       [0.16671044, 0.11114029, 0.24609636, 0.09526311, 0.02381578,
        0.07144733, 0.19052622, 0.03969296],
       [0.265194  , 0.        , 0.09359788, 0.06239859, 0.        ,
        0.09359788, 0.08579806, 0.00779982],
       [0.        , 0.16285367, 0.02124178, 0.        , 0.        ,
        0.00708059, 0.00708059, 0.        ],
       [0.46358435, 0.02357209, 0.07071626, 0.09428834, 0.00785736,
        0.00785736, 0.04714417, 0.        ],
       [0.06217789, 0.10881131, 0.18653368, 0.0854946 , 0.00777224,
        0.04663342, 0.03886118, 0.03108895],
       [0.05419676, 0.        , 0.03387298, 0.0067746 , 0.        ,
        0.        , 0.02709838, 0.02709838]])

In [250]:
idx_sort = np.argsort(mapped_data, axis=1)
idx_sort

array([[1, 4, 6, 7, 2, 3, 0, 5],
       [0, 3, 7, 5, 2, 6, 4, 1],
       [4, 7, 5, 3, 1, 0, 6, 2],
       [1, 4, 7, 3, 6, 2, 5, 0],
       [0, 3, 4, 7, 5, 6, 2, 1],
       [7, 4, 5, 1, 6, 2, 3, 0],
       [4, 7, 6, 5, 0, 3, 1, 2],
       [1, 4, 5, 3, 6, 7, 2, 0]])

In [251]:
def make_ribbon_ends(mapped_data, ideo_ends,  idx_sort):
    L = mapped_data.shape[0]
    ribbon_boundary = np.zeros((L,L+1))
    for k in range(L):
        start = ideo_ends[k][0]
        ribbon_boundary[k][0] = start
        for j in range(1,L+1):
            J = idx_sort[k][j-1]
            ribbon_boundary[k][j] = start + mapped_data[k][J]
            start = ribbon_boundary[k][j]
    return [[(ribbon_boundary[k][j], ribbon_boundary[k][j+1] ) for j in range(L)] for k in range(L)] 

In [252]:
ribbon_ends = make_ribbon_ends(mapped_data, ideo_ends,  idx_sort)
print ('ribbon ends starting from the ideogram[2]\n', ribbon_ends[2])

ribbon ends starting from the ideogram[2]
 [(2.91192008361456, 2.9357358608210853), (2.9357358608210853, 2.975428822831961), (2.975428822831961, 3.0468761544515375), (3.0468761544515375, 3.142139263277639), (3.142139263277639, 3.2532795569080912), (3.2532795569080912, 3.419989997353769), (3.419989997353769, 3.6105162150059726), (3.6105162150059726, 3.856612579473402)]


In [253]:
def control_pts(angle, radius):
    #angle is a  3-list containing angular coordinates of the control points b0, b1, b2
    #radius is the distance from b1 to the  origin O(0,0) 

    if len(angle) != 3:
        raise InvalidInputError('angle must have len =3')
    b_cplx = np.array([np.exp(1j*angle[k]) for k in range(3)])
    b_cplx[1] = radius * b_cplx[1]
    return list(zip(b_cplx.real, b_cplx.imag))

In [254]:
def ctrl_rib_chords(l, r, radius):
    # this function returns a 2-list containing control poligons of the two quadratic Bezier
    #curves that are opposite sides in a ribbon
    #l (r) the list of angular variables of the ribbon arc ends defining 
    #the ribbon starting (ending) arc 
    # radius is a common parameter for both control polygons
    if len(l) != 2 or len(r) != 2:
        raise ValueError('the arc ends must be elements in a list of len 2')
    return [control_pts([l[j], (l[j]+r[j])/2, r[j]], radius) for j in range(2)]

In [255]:
#Define ribbon color
ribbon_color = [L * ['rgba(175,175,175,0.5)'] for k in range(L)]

In [256]:
#Change 186 and 194 ribbon colors
for k_186 in range(len(ribbon_color[0])):
    ribbon_color[0][k_186] = ideo_colors[0]
for k_194 in range(len(ribbon_color[1])):
    ribbon_color[1][k_194] = ideo_colors[1]


In [257]:
def make_q_bezier(b):# defines the Plotly SVG path for a quadratic Bezier curve defined by the 
                     #list of its control points
    if len(b) != 3:
        raise valueError('control poligon must have 3 points')
    A, B, C = b    
    return f'M {A[0]}, {A[1]} Q {B[0]}, {B[1]} {C[0]}, {C[1]}'

In [258]:
b=[(1,4), (-0.5, 2.35), (3.745, 1.47)]
make_q_bezier(b)

'M 1, 4 Q -0.5, 2.35 3.745, 1.47'

In [259]:
def make_ribbon_arc(theta0, theta1):

    if test_2PI(theta0) and test_2PI(theta1):
        if theta0 < theta1:
            theta0 = moduloAB(theta0, -pi, pi)
            theta1 = moduloAB(theta1, -pi, pi)
            if theta0  *theta1 > 0:
                raise ValueError('incorrect angle coordinates for ribbon')
    
        nr = int(40 * (theta0 - theta1) / pi)
        if nr <= 2: nr = 3
        theta = np.linspace(theta0, theta1, nr)
        pts=np.exp(1j*theta)# points in polar complex form, on the given arc
    
        string_arc = ''
        for k in range(len(theta)):
            string_arc += f'L {pts.real[k]}, {pts.imag[k]} '
        return   string_arc 
    else:
        raise ValueError('the angle coordinates for an arc side of a ribbon must be in [0, 2*pi]')

In [260]:
make_ribbon_arc(np.pi/3, np.pi/6)

'L 0.5000000000000001, 0.8660254037844386 L 0.5877852522924732, 0.8090169943749473 L 0.6691306063588583, 0.7431448254773941 L 0.7431448254773942, 0.6691306063588581 L 0.8090169943749475, 0.5877852522924731 L 0.8660254037844387, 0.49999999999999994 '

In [261]:
def make_layout(title, plot_size):

    return dict(title=title,
                xaxis=dict(visible=False),
                yaxis=dict(visible=False),
                showlegend=False,
                width=plot_size,
                height=plot_size,
                margin=dict(t=25, b=25, l=25, r=25),
                hovermode=False,
                 )  

In [262]:
def make_ideo_shape(path, line_color, fill_color):
    #line_color is the color of the shape boundary
    #fill_color is the color assigned to an ideogram
    
    return  dict(line=dict(color=line_color, 
                           width=0.45),
                 path=path,
                 layer='below',
                 type='path',
                 fillcolor=fill_color)   

In [263]:
def make_ribbon(l, r, line_color, fill_color, radius=0.2):
    #l=[l[0], l[1]], r=[r[0], r[1]]  represent the opposite arcs in the ribbon 
    #line_color is the color of the shape boundary
    #fill_color is the fill color for the ribbon shape
    
    poligon = ctrl_rib_chords(l,r, radius)
    b, c = poligon  
           
    return  dict(line=dict(color=line_color, 
                             width=0.5),
                 path=make_q_bezier(b) + make_ribbon_arc(r[0], r[1])+
                         make_q_bezier(c[::-1]) + make_ribbon_arc(l[1], l[0]),
                 type='path',
                 layer='below',
                 fillcolor = fill_color,    
        )

def make_self_rel(l, line_color, fill_color, radius):
    #radius is the radius of Bezier control point b_1
    
    b = control_pts([l[0], (l[0]+l[1])/2, l[1]], radius) 
    
    return  dict(line = dict(color=line_color, 
                             width=0.5),
                 path =  make_q_bezier(b)+make_ribbon_arc(l[1], l[0]),
                 type = 'path',
                 layer = 'below',
                 fillcolor = fill_color   
                )

In [264]:
def invPerm(perm):
    # function that returns the inverse of a permutation, perm
    inv = [0] * len(perm)
    for i, s in enumerate(perm):
        inv[s] = i
    return inv

In [265]:
layout=make_layout('Pairwise interactions between common egg mutation genotypes', 800)   

In [266]:
ribbon_info=[]
shapes=[]
annotations = []
for k in range(L):
    
    sigma = idx_sort[k]
    sigma_inv = invPerm(sigma)
    for j in range(k, L):
        if matrix[k][j] == 0 and matrix[j][k]==0: continue
        eta = idx_sort[j]
        eta_inv = invPerm(eta)
        l = ribbon_ends[k][sigma_inv[j]]  
        
        if j == k:
            shapes.append(make_self_rel(l, 'rgba(175,175,175,0.5)',
                                        'rgba(175,175,175,0.5)', radius=radii_sribb[k])) 
#             shapes.append(make_self_rel(l, ideo_colors[k] ,
#                         ideo_colors[k], radius=radii_sribb[k])) 

            z = 0.9*np.exp(1j*(l[0]+l[1])/2)
            

            ribbon_info.append(go.Scatter(x=[z.real],
                                       y=[z.imag],
                                       mode='markers',
                                       marker=dict(size=0.5, color=ideo_colors[k])
                                       )
                              )
        else:
            r = ribbon_ends[j][eta_inv[k]]
            zi = 0.9 * np.exp(1j*(l[0]+l[1])/2)
            zf = 0.9 * np.exp(1j*(r[0]+r[1])/2)
            #texti and textf are the strings that will be displayed when hovering the mouse 
            #over the two ribbon ends
            texti = f'{labels[k]}'
            textf = f'{labels[j]}'
            
            ribbon_info.append(go.Scatter(x=[zi.real],
                                          y=[zi.imag],
                                          mode='markers',
                                          marker=dict(size=0.5, color=ribbon_color[k][j]),
                                          text=texti
                                       )
                              ),
            ribbon_info.append(go.Scatter(x=[zf.real],
                                          y=[zf.imag],
                                          mode='markers',
                                          marker=dict(size=0.5, color=ribbon_color[k][j]),
                                          text=textf
                                       )
                              )
            r = (r[1], r[0]) # IMPORTANT!!!  Reverse these arc ends because otherwise you get
                          # a twisted ribbon
            #append the ribbon shape
            shapes.append(make_ribbon(l, r, ribbon_color[k][j] , ribbon_color[k][j]))
           
                                    

In [267]:
ideograms = []
for k in range(len(ideo_ends)):
    z =  make_ideogram_arc(1.1, ideo_ends[k])
    zi = make_ideogram_arc(1.0, ideo_ends[k])
    m = len(z)
    n = len(zi)
    ideograms.append(go.Scatter(x=z.real,
                                y=z.imag,
                                mode='lines',
                                line=dict(color=ideo_colors[k], shape='spline', width=0.25)
#                                 text=f'{labels[k]} <br>{int(row_sum[k])} viruses'
                             )
                     )
    
       
    path = 'M '
    for s in range(m):
        path += f'{z.real[s]}, {z.imag[s]} L '
        
    Zi = np.array(zi.tolist()[::-1]) 

    for s in range(m):
        path += f'{Zi.real[s]}, {Zi.imag[s]} L '
    path += f'{z.real[0]} ,{z.imag[0]}' 
   
    shapes.append(make_ideo_shape(path,ideo_colors[k] , ideo_colors[k]))
    
    z_text =  make_ideogram_arc(1.2, ideo_ends[k])
    Z_text = np.array(z_text.tolist()[::-1]) 
    annotations.append(dict(x=Z_text.real[int(len(Z_text)/2)], 
                            y=Z_text.imag[int(len(Z_text)/2)], 
                            showarrow=False,
                            align='left',
                            valign='bottom',
                            text=f'{labels[k]}'))


In [268]:
data = ideograms + ribbon_info
layout['shapes'] = shapes
layout['annotations'] = annotations
fig = go.Figure(data=data, layout=layout)
from plotly.offline import download_plotlyjs, init_notebook_mode,  iplot, plot
init_notebook_mode(connected=True)
iplot(fig)